<?php
vc_map(array(
    "name"            => __("Fade Text Box", "mk_framework"),
    "base"            => "mk_fade_txt_box",
    "content_element" => true,
    'icon'            => 'icon-mk-content-box vc_mk_element-icon',
    "as_parent"       => array('only' => 'mk_fade_txt_item'),
    "category"        => __('Slideshows', 'mk_framework'),
    'params'          => array(
        array(
            "type"       => "range",
            "heading"    => __("Item Padding", "mk_framework"),
            "param_name" => "padding",
            "value"      => "20",
            "min"        => "5",
            "max"        => "500",
            "step"       => "1",
            "unit"       => 'px',
        ),
        array(
            "type"        => "range",
            "heading"     => __("Animation Speed", "mk_framework"),
            "param_name"  => "animation_speed",
            "value"       => "700",
            "min"         => "100",
            "max"         => "3000",
            "step"        => "1",
            "unit"        => 'ms',
            "description" => __("", "mk_framework"),
        ),
        array(
            "heading"     => __("Slideshow Speed", "mk_framework"),
            "param_name"  => "slideshow_speed",
            "value"       => "5000",
            "min"         => "0",
            "max"         => "50000",
            "step"        => "1",
            "unit"        => 'ms',
            "description" => __("If set to zero the autoplay will be disabled, any number above zeo will define the delay between each slide transition.", "mk_framework"),
            'type'        => 'range',
        ),
        array(
            "type"        => "textfield",
            "heading"     => __("Extra class name", "mk_framework"),
            "param_name"  => "el_class",
            "value"       => "",
            "description" => __("If you wish to style particular content element differently, then use this field to add a class name and then refer to it in Custom CSS Shortcode or Masterkey Custom CSS option.", "mk_framework"),
        ),
    ),
    "js_view"         => 'VcColumnView',
));