<?php
vc_map(array(
    "name"        => __("Gradient Text", "mk_framework"),
    "base"        => "mk_gradient_text",
    'icon'        => '',
    "category"    => __('Typography', 'mk_framework'),
    'description' => __('', 'mk_framework'),
    "params"      => array(
        array(
            "type"        => "textfield",
            "heading"     => __("Gradient Text", "mk_framework"),
            "param_name"  => "text",
            "value"       => __("", "mk_framework"),
            "description" => __("", "mk_framework"),
        ),
        array(
            "type"        => "dropdown",
            "heading"     => __("Align.", "mk_framework"),
            "param_name"  => "text_align",
            "value"       => array(
                __('Left', "mk_framework")   => "left",
                __('Center', "mk_framework") => "center",
                __('Right', "mk_framework")  => "right",
            ),
            "description" => __("", "mk_framework"),
        ),
        array(
            "type"        => "theme_fonts",
            "heading"     => __("Font Family", "mk_framework"),
            "param_name"  => "font_family",
            "value"       => "",
            "description" => __("You can choose a font for this shortcode, however using non-safe fonts can affect page load and performance.", "mk_framework"),
        ),
        array(
            "type"        => "hidden_input",
            "param_name"  => "font_type",
            "value"       => "",
            "description" => __("", "mk_framework"),
        ),
        array(
            "type"        => "range",
            "heading"     => __("Font Size", "mk_framework"),
            "param_name"  => "font_size",
            "value"       => "14",
            "min"         => "12",
            "max"         => "100",
            "step"        => "1",
            "unit"        => 'px',
            "description" => __("", "mk_framework"),
        ),
        array(
            "type"        => "dropdown",
            "heading"     => __("Font Weight", "mk_framework"),
            "param_name"  => "font_weight",
            "width"       => 150,
            "value"       => array(
                __('Default', "mk_framework")   => "inherit",
                __('Bolder (900)', "mk_framework")    => "900",
                __('Bolder (800)', "mk_framework")    => "bolder",
                __('Bold (700)', "mk_framework")      => "bold",
                __('Semi Bold (600)', "mk_framework") => "600",
                __('Medium (500)', "mk_framework")    => "500",
                __('Normal (400)', "mk_framework")    => "normal",
                __('Light (300)', "mk_framework")     => "300",
                __('Lighter (200)', "mk_framework")     => "200",
                __('Lighter (100)', "mk_framework")     => "100",
            ),
            "description" => __("", "mk_framework"),
        ),
        array(
            "type"        => "dropdown",
            "heading"     => __("Gradient Style Orientation", "mk_framework"),
            "param_name"  => "gradient_style",
            "width"       => 150,
            "value"       => array(
                __('Vertical ', "mk_framework")    => "vertical",
                __('Horizontal →', "mk_framework") => "horizontal",
                __('Radial ○', "mk_framework")     => "radial",
            ),
            "description" => __("Choose the orientation of gradient style", "mk_framework"),
        ),
        array(
            "type"        => "colorpicker",
            "heading"     => __("Start Color", "mk_framework"),
            "param_name"  => "start_color",
            "value"       => $skin_color,
            "description" => __("", "mk_framework"),
        ),
        array(
            "type"        => "colorpicker",
            "heading"     => __("End Color", "mk_framework"),
            "param_name"  => "end_color",
            "value"       => '#ccc',
            "description" => __("", "mk_framework"),
        ),
        $add_device_visibility,
        array(
            "type"        => "textfield",
            "heading"     => __("Extra class name", "mk_framework"),
            "param_name"  => "el_class",
            "value"       => "",
            "description" => __("If you wish to style particular content element differently, then use this field to add a class name and then refer to it in your css file.", "mk_framework"),
        ),
    ),
));