<?php
vc_map(array(
    "name"            => __("Step", "mk_framework"),
    "base"            => "mk_step",
    "content_element" => true,
    "as_child"        => array('only' => 'mk_process_steps'),
    "is_container"    => true,
    'icon'            => 'icon-mk-process-builder vc_mk_element-icon',
    "params"          => array(
        array(
            "type"        => "textfield",
            "heading"     => __("Title", "mk_framework"),
            "param_name"  => "title",
            "description" => __("", "mk_framework"),
        ),

        array(
            "type"        => "range",
            "heading"     => __("Title Font Size?", "mk_framework"),
            "param_name"  => "font_size",
            "value"       => "16",
            "min"         => "10",
            "max"         => "50",
            "step"        => "1",
            "unit"        => 'px',
            "description" => __("", "mk_framework"),
        ),
        array(
            "type"        => "range",
            "heading"     => __("Title Line Height?", "mk_framework"),
            "param_name"  => "line_height",
            "value"       => "16",
            "min"         => "10",
            "max"         => "50",
            "step"        => "1",
            "unit"        => 'px',
            "description" => __("", "mk_framework"),
        ),
        array(
            "type"        => "range",
            "heading"     => __("Title Margin Bottom?", "mk_framework"),
            "param_name"  => "margin_bottom",
            "value"       => "10",
            "min"         => "5",
            "max"         => "25",
            "step"        => "1",
            "unit"        => 'px',
            "description" => __("", "mk_framework"),
        ),
        array(
            "type"        => "dropdown",
            "heading"     => __("Title Font Weight", "mk_framework"),
            "param_name"  => "font_weight",
            "width"       => 150,
            "value"       => array(
                __('Default', "mk_framework")   => "inherit",
                __('Bolder (900)', "mk_framework")    => "900",
                __('Bolder (800)', "mk_framework")    => "bolder",
                __('Bold (700)', "mk_framework")      => "bold",
                __('Semi Bold (600)', "mk_framework") => "600",
                __('Medium (500)', "mk_framework")    => "500",
                __('Normal (400)', "mk_framework")    => "normal",
                __('Light (300)', "mk_framework")     => "300",
                __('Lighter (200)', "mk_framework")     => "200",
                __('Lighter (100)', "mk_framework")     => "100",
            ),
            "description" => __("", "mk_framework"),
        ),
        array(
            "type"        => "textarea",
            "heading"     => __("Short Description", "mk_framework"),
            "param_name"  => "desc",
            "description" => __("", "mk_framework"),
        ),

        array(
            "type"        => "textfield",
            "heading"     => __("Add Icon Class Name", "mk_framework"),
            "param_name"  => "icon",
            "value"       => "mk-li-smile",
            "description" => __("<a target='_blank' href='" . admin_url('admin.php?page=icon-library') . "'>Click here</a> to get the icon class name (or any other font icons library that you have installed in the theme)", "mk_framework"),
        ),
    ),
    "js_view"         => 'VcColumnView',
));